USE ROLE ACCOUNTADMIN;
USE DATABASE GOVERNANCE_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TAG DATA_SENSITIVITY
    ALLOWED_VALUES ('PII','CONFIDENTIAL','INTERNAL','PUBLIC');

CREATE OR REPLACE TABLE GOVERNANCE_AUTOPILOT_LOG (
    EVENT_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    OBJECT_TYPE STRING,
    OBJECT_NAME STRING,
    COLUMN_NAME STRING,
    ACTION STRING,
    DETAILS STRING
);
