USE DATABASE GOVERNANCE_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE FUNCTION NOTIFY_SLACK(payload VARIANT)
RETURNS STRING
LANGUAGE SQL
AS
$$ SELECT 'Simulated Slack: ' || payload::string; $$;

CREATE OR REPLACE PROCEDURE AUTOPILOT_ALERT_UNTAGGED()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE v_count INTEGER := 0;
BEGIN
  FOR rec IN (
    SELECT TABLE_SCHEMA, TABLE_NAME
    FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_TYPE='BASE TABLE'
    AND NOT EXISTS (
      SELECT 1
      FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_TAGS ot
      WHERE ot.OBJECT_NAME = TABLE_NAME
      AND ot.TAG_NAME='DATA_SENSITIVITY'
    )
  )
  DO
    SELECT NOTIFY_SLACK(OBJECT_CONSTRUCT('text','New untagged table: '||rec.TABLE_SCHEMA||'.'||rec.TABLE_NAME));

    INSERT INTO GOVERNANCE_AUTOPILOT_LOG(OBJECT_TYPE,OBJECT_NAME,ACTION,DETAILS)
    VALUES('TABLE',rec.TABLE_SCHEMA||'.'||rec.TABLE_NAME,'ALERT_UNTAGGED_TABLE','Missing tags');

    v_count := v_count + 1;
  END FOR;

  RETURN 'Processed '||v_count||' untagged tables.';
END;
$$;

CREATE OR REPLACE TASK AUTOPILOT_GOVERNANCE_TASK
WAREHOUSE=COMPUTE_WH
SCHEDULE='5 MINUTE'
AS
CALL AUTOPILOT_ALERT_UNTAGGED();
